### ISSUE TITLE
Quest description of clothing fails in r 11v5.0 and up

### ISSUE THREAD

**Issue by Elmesyge** [aika092/TrapQuest#43]
Since 5.0 introduced a message about not completing quests at the school, description of quests on items has been broken.

The description references FullQuestFlav of a clothing item, which isn't defined.

https://github.com/aika092/TrapQuest/blob/e67ab5aada2648eead7c95b27c207abf18a70745/Trap%20Quest.inform/Inform/Extensions/Clothing/Quests.i7x

needs a forwarding from clothing to quest for quest full quest flavour

```
To say FullQuestFlav of (C - a clothing):
	say FullQuestFlav of the quest of C.
```

should do the trick

**Comment by aika092** [comment]
Yep thanks already fixed in the private repo and ready for the next version ❤️
